name: Unit testing and Integration testing [development]
on:
  push:
    branches:
      - development

  pull_request:
    types: [opened, synchronize]   
  
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: 'Branch' 
        default: 'development'
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: prancer-io/cloud-validation-framework 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: testing
        run: |
          docker run --rm -v $(pwd):$(pwd) -w=$(pwd) python:3.6.8 sh dev-test.sh
          docker run --rm -v $(pwd):$(pwd) -w=$(pwd) python:3.8 sh dev-test.sh
          docker run --rm -v $(pwd):$(pwd) -w=$(pwd) python:3.9 sh dev-test.sh
